drop function if exists public.document_status(uuid);
drop view if exists public.document_balances_v;
-- functions that take a transactions row depend on the table's type
drop function if exists public._fx_balance(public.transactions);
drop function if exists public._post_rules(public.transactions);
drop function if exists public._recalc_lines(public.transactions);
drop function if exists public._payout_gate(public.transactions);
drop function if exists public._check_claim(public.transactions);
drop function if exists public._money_account(public.transactions, text);
drop function if exists public._split(public.transactions, uuid, numeric, uuid, uuid);
drop function if exists public._jl(public.transactions, uuid, numeric, uuid, uuid, uuid, text, text, uuid);
drop table if exists public.attachments;
drop table if exists public.applications;
drop table if exists public.journal_lines;
drop table if exists public.transaction_lines;
drop table if exists public.transactions;
drop table if exists public.items;
drop function if exists public.check_application();
drop function if exists public.guard_claimable();
drop function if exists public.guard_txn_delete();
drop function if exists public.guard_lines_closing();
drop function if exists public.guard_closing_date();
drop function if exists public.check_balanced();
drop function if exists public.void_transaction(uuid, text);
drop function if exists public.post_transaction(uuid);
drop function if exists public._after_post(uuid, uuid[]);
drop function if exists public._gst_after_post(uuid);
drop function if exists public._line_frozen(uuid);
drop function if exists public.doc_total(uuid);
drop function if exists public.today_mv();
drop type if exists public.txn_type;
