drop function if exists public.bills_paid_since(date);
drop view if exists public.expenses_list_v;
drop view if exists public.committed_cost_v;
drop function if exists public.rpc_close_po(uuid, boolean);
drop function if exists public.rpc_bill_from_po(uuid, date);
drop function if exists public.rpc_apply_credit(uuid, uuid, numeric);
drop function if exists public.rpc_pay_bills(uuid, date, jsonb, text);
drop function if exists public.pay_bills(uuid, date, jsonb, text);
drop function if exists public.rpc_approve_bill(uuid);
drop function if exists public.rpc_request_approval(uuid);
drop trigger if exists transactions_bill_approval on public.transactions;
drop function if exists public.check_bill_approval();
alter table public.transactions drop column if exists closed_at;
alter table public.transactions drop column if exists purchase_order_id;
alter table public.transactions drop column if exists approved_total;
drop trigger if exists vendors_mirror_contact on public.vendors;
drop trigger if exists contacts_mirror_vendor on public.contacts;
drop function if exists public.mirror_vendor_to_contact();
drop function if exists public.mirror_contact_to_vendor();
